# Import libraries , data and declraring variables

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [36]:
data = pd.read_csv('sample6.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [37]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [38]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

# Regression

In [74]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [75]:
reg.intercept_

0.29603261264909353

In [76]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [41]:
x.shape

(84, 2)

In [39]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [42]:
r_sq = reg.score(x,y)
r_sq

0.40668119528142815

In [43]:
n = x.shape[0]
p = x.shape[1]
adj_rsq = 1 - ((1-r_sq)*(n-r_sq)/(n-p-1))
adj_rsq

0.38768533338673905

# Standardisation

In [44]:
from sklearn.feature_selection import f_regression
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [45]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [46]:
p_values.round(3)

array([0.   , 0.676])

# Summary Table with sklearn

In [47]:
reg_summary = pd.DataFrame(data=x.columns.values , columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [48]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)
reg_summary['Coefficients']

0    0.001654
1   -0.008270
Name: Coefficients, dtype: float64

In [49]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

# Standardization with sklearn

In [50]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [51]:
xscaled = scaler.transform(x)
xscaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

# Regression with scaled features

In [61]:
reg = LinearRegression()
reg.fit(xscaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [62]:
reg = LinearRegression()
reg.fit(xscaled,y)
print(reg.coef_)
print(reg.intercept_)

[ 0.17181389 -0.00703007]
3.330238095238095


In [63]:
reg.coef_

array([ 0.17181389, -0.00703007])

# Creating summary table 

In [64]:
reg_summary = pd.DataFrame([['intercept'] , ['SAT'],['Rand 1,2,3']] , columns  = ['Features'])
reg_summary['Weights'] = reg.intercept_ , reg.coef_[0] , reg.coef_[1]
reg_summary

Features   Weights
0   intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

# Making Prediction with Standardized Coeff. 

In [65]:
new_data = pd.DataFrame(data=[[1700 , 2] , [1900 , 1]] , columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1900           1

In [66]:
print(reg.predict(new_data))
new_dataScaled = scaler.transform(new_data)
new_dataScaled

[295.39979563 329.76960424]


array([[-1.39811928, -0.07002087],
       [ 0.52668642, -1.24637147]])

In [67]:
reg.predict(new_dataScaled)

array([3.09051403, 3.42949221])

# When we remove 'Random 1,2,3'

In [70]:
reg_simple = LinearRegression()
x_simple = xscaled[: , 0].reshape(-1,1)
reg_simple.fit(x_simple,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [71]:
reg_simple.predict(new_dataScaled[:,0].reshape(-1,1))          

array([3.08970998, 3.42084759])